sonar.projectKey=django_project
sonar.projectName=Django Project
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.x
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc
