# Generated by Django 5.1.4 on 2025-04-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataEngine', '0006_delete_datemaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationMaster',
        ),
    ]
