# Generated by Django 5.1.4 on 2025-05-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataEngine', '0007_delete_operationmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillTable',
        ),
    ]
