# Generated by Django 5.1.4 on 2025-05-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEngine', '0008_delete_skilltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'db_table': 'payable_working_days',
            },
        ),
    ]
