# Generated by Django 5.1.4 on 2026-06-25 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenteeismPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
                ('day_of_week', models.CharField(default='NA', max_length=25)),
                ('predicted_absent_count', models.FloatField()),
                ('line', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('forecast_period', models.IntegerField()),
                ('historical_mean', models.FloatField()),
                ('historical_std', models.FloatField()),
                ('deviation_from_mean', models.FloatField()),
            ],
            options={
                'db_table': 'absenteeism_prediction',
            },
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('empcode', models.CharField(max_length=20, verbose_name='Employee Code')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('section', models.CharField(max_length=100, null=True, verbose_name='Section')),
                ('attendance', models.CharField(default='A', max_length=30)),
            ],
            options={
                'db_table': 'absenteeism_data',
            },
        ),
        migrations.CreateModel(
            name='Absenteeism',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('empcode', models.CharField(db_index=True, max_length=20, verbose_name='Employee Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('doj', models.DateField(null=True, verbose_name='Date of Joining')),
                ('attendance', models.CharField(default='A', max_length=30)),
                ('present_days', models.IntegerField(default=0, null=True, verbose_name='Present Days')),
                ('weekly_offs', models.IntegerField(default=0, null=True, verbose_name='Weekly Offs')),
                ('holidays', models.IntegerField(default=0, null=True, verbose_name='Holidays')),
                ('leaves', models.IntegerField(default=0, null=True, verbose_name='Leaves')),
                ('absent_days', models.IntegerField(default=0, null=True, verbose_name='Absent Days')),
                ('double_present', models.IntegerField(default=0, null=True, verbose_name='Double Present')),
                ('overtime_hours', models.IntegerField(default=0, null=True, verbose_name='Overtime Hours')),
            ],
            options={
                'db_table': 'absenteeism_master',
                'ordering': ['-date'],
                'unique_together': {('date', 'empcode')},
            },
        ),
    ]
