# Generated by Django 5.1.4 on 2025-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenteeismPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('absent_count', models.FloatField(blank=True, null=True)),
                ('total_employees', models.FloatField(blank=True, null=True)),
                ('absenteeism_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'absenteeism_percentage',
            },
        ),
    ]
