# Generated by Django 5.1.4 on 2026-06-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0002_absenteeism_created_at_absenteeism_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeism',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='department',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='section',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Section'),
        ),
    ]
