# Generated by Django 5.1.4 on 2025-05-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0002_absenteeismpercentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbsenteeismPercentage',
        ),
    ]
