# Generated by Django 5.1.4 on 2026-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0003_alter_absenteeism_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absenteeism',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='absenteeismprediction',
            name='datetime',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='absenteeismprediction',
            name='line',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='absenteeismprediction',
            name='section',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='empcode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Employee Code'),
        ),
        migrations.AddConstraint(
            model_name='absenteeism',
            constraint=models.UniqueConstraint(fields=('date', 'empcode'), name='unique_absenteeism_date_empcode'),
        ),
        migrations.AddConstraint(
            model_name='absenteeismprediction',
            constraint=models.UniqueConstraint(fields=('datetime', 'line', 'section', 'forecast_period'), name='unique_absenteeism_prediction'),
        ),
        migrations.AddConstraint(
            model_name='predictiondata',
            constraint=models.UniqueConstraint(fields=('date', 'empcode'), name='unique_prediction_data_date_empcode'),
        ),
    ]
