# Generated by Django 5.1.4 on 2026-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absenteeism', '0003_delete_absenteeismpercentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absenteeism',
            old_name='Ab',
            new_name='absent_days',
        ),
        migrations.RenameField(
            model_name='absenteeism',
            old_name='DP',
            new_name='double_present',
        ),
        migrations.RenameField(
            model_name='absenteeism',
            old_name='H',
            new_name='holidays',
        ),
        migrations.RenameField(
            model_name='absenteeism',
            old_name='L',
            new_name='leaves',
        ),
        migrations.RenameField(
            model_name='absenteeism',
            old_name='OT1',
            new_name='overtime_hours',
        ),
        migrations.RenameField(
            model_name='absenteeism',
            old_name='P',
            new_name='present_days',
        ),
        migrations.RenameField(
            model_name='absenteeism',
            old_name='WO',
            new_name='weekly_offs',
        ),
        migrations.AlterField(
            model_name='absenteeism',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='absenteeism',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='absenteeism',
            name='empcode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Employee Code'),
        ),
        migrations.AlterField(
            model_name='absenteeism',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name'),
        ),
        migrations.AlterUniqueTogether(
            name='absenteeism',
            unique_together={('date', 'empcode')},
        ),
    ]
