# Generated by Django 5.1.4 on 2025-03-20 08:45

import apps.accounts.models as accounts_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisessiontoken',
            name='expiry',
            field=models.DateTimeField(default=accounts_models.default_expiry),
        ),
    ]
