# Generated by Django 5.2.5 on 2026-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_multisessiontoken_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointlock',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Admin')], default=0),
        ),
    ]
