# Generated by Django 5.1.4 on 2025-05-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_endpointlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
