# Generated by Django 5.1.4 on 2026-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endpointlock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('lock_type', 'url_name'), name='unique_active_lock'),
        ),
    ]
