# Generated by Django 5.1.4 on 2025-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=50)),
                ('factory', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
                ('last_updated', models.TimeField()),
                ('status', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('early_departure', models.BooleanField()),
            ],
            options={
                'db_table': 'attendance_master',
            },
        ),
        migrations.CreateModel(
            name='DateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('days', models.IntegerField()),
            ],
            options={
                'db_table': 'date_master',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('emp_code', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('line', models.CharField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=40)),
                ('primary', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'employee_master',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('tempmax', models.FloatField()),
                ('tempmin', models.FloatField()),
                ('temp', models.FloatField()),
                ('feelslikemax', models.FloatField()),
                ('feelslikemin', models.FloatField()),
                ('feelslike', models.FloatField()),
                ('dew', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precip', models.FloatField()),
                ('precipprob', models.FloatField()),
                ('precipcover', models.FloatField(blank=True, null=True)),
                ('preciptype', models.CharField(blank=True, max_length=255, null=True)),
                ('snow', models.FloatField(blank=True, null=True)),
                ('snowdepth', models.FloatField(blank=True, null=True)),
                ('windgust', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('winddir', models.FloatField()),
                ('sealevelpressure', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('visibility', models.FloatField()),
                ('solarradiation', models.FloatField()),
                ('solarenergy', models.FloatField()),
                ('uvindex', models.IntegerField()),
                ('severerisk', models.IntegerField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('moonphase', models.FloatField()),
                ('conditions', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
                ('stations', models.TextField()),
            ],
            options={
                'db_table': 'historical_weather',
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('event', models.CharField(default=None, max_length=255)),
                ('leave_type', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalHolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('event', models.CharField(max_length=100)),
                ('leave_type', models.CharField(default='full', max_length=100)),
            ],
            options={
                'db_table': 'local_holiday_calendar',
            },
        ),
        migrations.CreateModel(
            name='OperationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ops_code', models.CharField(blank=True, max_length=255)),
                ('ops_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('is_inUse', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'operation_master',
            },
        ),
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('operator_name', models.CharField(max_length=255)),
                ('ops_code', models.IntegerField()),
                ('operation', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('skill_type', models.CharField(max_length=255)),
                ('peak_capacity', models.FloatField()),
                ('peak_performance', models.FloatField()),
                ('avg_capacity', models.FloatField()),
                ('avg_performance', models.FloatField()),
                ('avg_dhu', models.FloatField()),
                ('machinist', models.BooleanField()),
            ],
            options={
                'db_table': 'skill_matrix',
            },
        ),
        migrations.CreateModel(
            name='SkillTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=255)),
                ('employee_id', models.IntegerField()),
                ('line', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('sam_x', models.FloatField()),
                ('target_capacity', models.IntegerField()),
                ('peak_capacity', models.IntegerField()),
                ('average_capacity', models.IntegerField(blank=True, null=True)),
                ('difference', models.FloatField()),
                ('operation_type', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('machinist', models.CharField(max_length=10)),
                ('machine_type', models.CharField(max_length=100)),
                ('sam_y', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'skill_table',
            },
        ),
        migrations.CreateModel(
            name='LoadPlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.PositiveIntegerField()),
                ('oc_number', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.CharField(max_length=255)),
                ('ops_code', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'load_plan_data',
                'unique_together': {('weeks', 'oc_number', 'order_number', 'style', 'line')},
            },
        ),
    ]
