# Generated by Django 5.1.4 on 2026-06-25 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=50)),
                ('factory', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
                ('last_updated', models.TimeField()),
                ('status', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('early_departure', models.BooleanField()),
            ],
            options={
                'db_table': 'attendance_master',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_code', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=40)),
                ('primary', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'employee_master',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
                ('tempmax', models.FloatField()),
                ('tempmin', models.FloatField()),
                ('temp', models.FloatField()),
                ('feelslikemax', models.FloatField()),
                ('feelslikemin', models.FloatField()),
                ('feelslike', models.FloatField()),
                ('dew', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precip', models.FloatField()),
                ('precipprob', models.FloatField()),
                ('precipcover', models.FloatField(blank=True, null=True)),
                ('preciptype', models.CharField(blank=True, max_length=255, null=True)),
                ('snow', models.FloatField(blank=True, null=True)),
                ('snowdepth', models.FloatField(blank=True, null=True)),
                ('windgust', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('winddir', models.FloatField()),
                ('sealevelpressure', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('visibility', models.FloatField()),
                ('solarradiation', models.FloatField()),
                ('solarenergy', models.FloatField()),
                ('uvindex', models.IntegerField()),
                ('severerisk', models.IntegerField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('moonphase', models.FloatField()),
                ('conditions', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
                ('stations', models.TextField()),
            ],
            options={
                'db_table': 'historical_weather',
            },
        ),
        migrations.CreateModel(
            name='LocalHolidayCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('event', models.CharField(max_length=100)),
                ('leave_type', models.CharField(default='full', max_length=100)),
            ],
            options={
                'db_table': 'local_holiday_calendar',
            },
        ),
        migrations.CreateModel(
            name='PayableWorkingDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'db_table': 'payable_working_days',
            },
        ),
    ]
