# Generated by Django 5.2.5 on 2026-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0002_attendancemaster_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalweather',
            name='datetime',
            field=models.DateField(db_index=True),
        ),
    ]
