# Generated by Django 5.1.4 on 2025-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0002_delete_attendancemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=50)),
                ('factory', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('attendance_date', models.DateField()),
                ('last_updated', models.TimeField()),
                ('status', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('early_departure', models.BooleanField()),
            ],
            options={
                'db_table': 'attendance_master',
            },
        ),
    ]
