# Generated by Django 5.1.4 on 2025-03-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0004_delete_holidaycalendar_delete_loadplandata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillMatrix',
        ),
    ]
