# Generated by Django 5.1.4 on 2025-04-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0005_delete_skillmatrix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateMaster',
        ),
    ]
