# Generated by Django 5.1.4 on 2026-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0009_payableworkingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
