# Generated by Django 5.1.4 on 2025-03-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manningsheetdata',
            name='smv',
            field=models.FloatField(default=0),
        ),
    ]
