# Generated by Django 5.1.4 on 2026-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0002_activeemployees_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeemployees',
            name='employee_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeemployees',
            name='line',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='allocated_emp_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='line',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='planned_dates',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loadingplan',
            name='date_end',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadingplan',
            name='date_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadingplan',
            name='line',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loadingplan',
            name='planned_dates',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='manningsheetdata',
            name='allocated_emp_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='manningsheetdata',
            name='line',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manningsheetdata',
            name='planned_dates',
            field=models.DateField(db_index=True),
        ),
    ]
