# Generated by Django 5.1.4 on 2025-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0002_manningsheetdata_smv'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleob',
            name='color',
            field=models.CharField(default='Black', max_length=255),
        ),
        migrations.AddField(
            model_name='styleob',
            name='machine_type',
            field=models.CharField(default='Machine Type', max_length=255),
        ),
        migrations.AddField(
            model_name='styleob',
            name='machinist',
            field=models.CharField(default='False', max_length=255),
        ),
    ]
