# Generated by Django 5.1.4 on 2025-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0003_styleob_color_styleob_machine_type_styleob_machinist'),
    ]

    operations = [
        migrations.AddField(
            model_name='manningsheetdata',
            name='machine_type',
            field=models.CharField(default='Machine Type', max_length=255),
        ),
        migrations.AddField(
            model_name='manningsheetdata',
            name='machinist',
            field=models.CharField(default='False', max_length=255),
        ),
    ]
