# Generated by Django 5.1.4 on 2026-07-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0003_alter_activeemployees_employee_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ddaydata',
            index=models.Index(fields=['line', 'planned_dates'], name='idx_dday_line_dates'),
        ),
        migrations.AddIndex(
            model_name='manningsheetdata',
            index=models.Index(fields=['line', 'planned_dates'], name='idx_manning_line_dates'),
        ),
    ]
