# Generated by Django 5.1.4 on 2025-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0004_manningsheetdata_machine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manningsheetdata',
            name='color',
            field=models.CharField(default='Black', max_length=255),
        ),
    ]
