# Generated by Django 5.1.4 on 2025-03-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0005_manningsheetdata_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddaydata',
            name='attendance_status',
            field=models.CharField(default='P', max_length=255),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='average_capacity_per_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='backlog_flag',
            field=models.CharField(default='Back Log', max_length=255),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='color',
            field=models.CharField(default='Black', max_length=255),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='machine_type',
            field=models.CharField(default='Machine Type', max_length=255),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='machinist',
            field=models.CharField(default='False', max_length=255),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='original_emp_name',
            field=models.CharField(default='Original Employee Name', max_length=255),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='original_planned_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ddaydata',
            name='smv',
            field=models.FloatField(default=0),
        ),
    ]
