# Generated by Django 5.1.4 on 2025-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0006_ddaydata_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddaydata',
            name='attendance_status',
            field=models.CharField(blank=True, default='P', max_length=255, null=True),
        ),
    ]
