# Generated by Django 5.1.4 on 2025-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0007_alter_ddaydata_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddaydata',
            name='average_capacity_per_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='backlog_flag',
            field=models.CharField(blank=True, default='Back Log', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='color',
            field=models.CharField(blank=True, default='Black', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='machine_type',
            field=models.CharField(blank=True, default='Machine Type', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='machinist',
            field=models.CharField(blank=True, default='False', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='original_emp_name',
            field=models.CharField(blank=True, default='Original Employee Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='original_planned_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ddaydata',
            name='smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
