# Generated by Django 5.1.4 on 2025-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0008_alter_ddaydata_average_capacity_per_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_no', models.CharField(max_length=255)),
                ('order_no', models.CharField(max_length=255)),
                ('buyer', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('line', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('op_seq', models.IntegerField()),
                ('operation', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('wip_qty', models.FloatField()),
            ],
            options={
                'db_table': 'wip_data',
            },
        ),
    ]
