# Generated by Django 5.1.4 on 2025-03-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0009_wipdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddaydata',
            name='final_allocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
