# Generated by Django 5.1.4 on 2025-03-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0010_ddaydata_final_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillShortages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('period', models.IntegerField()),
                ('shortage_qty', models.FloatField()),
            ],
            options={
                'db_table': 'skill_shortages',
            },
        ),
    ]
