# Generated by Django 5.1.4 on 2025-03-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0011_skillshortages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnallocatesEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('initial_capacity', models.FloatField()),
                ('remaining_capacity', models.FloatField()),
                ('utilization_pct', models.FloatField()),
                ('reason', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=500)),
                ('period', models.IntegerField()),
            ],
            options={
                'db_table': 'unallocated_employees',
            },
        ),
    ]
