# Generated by Django 5.1.4 on 2025-04-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0013_alter_skillshortages_code_alter_skillshortages_line_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnallocatesEmployees',
            new_name='UnallocatedEmployees',
        ),
    ]
