# Generated by Django 5.1.4 on 2025-04-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0016_alter_pushnotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('machinist', models.CharField(default='False', max_length=255)),
                ('service_years', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'active_employees',
            },
        ),
    ]
