# Generated by Django 5.1.4 on 2025-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0017_activeemployees'),
    ]

    operations = [
        migrations.AddField(
            model_name='manninggeneralinfo',
            name='planned_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
