# Generated by Django 5.1.4 on 2025-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0018_manninggeneralinfo_planned_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unallocatedemployees',
            name='date',
            field=models.DateField(),
        ),
    ]
