# Generated by Django 5.1.4 on 2025-05-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0020_alter_pushnotification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='styleob',
            name='color',
        ),
    ]
