# Generated by Django 5.1.4 on 2025-05-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0021_remove_styleob_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingplan',
            name='raw_fabric_article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadingplan',
            name='raw_oc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadingplan',
            name='raw_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
