# Generated by Django 5.1.4 on 2025-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0022_loadingplan_raw_fabric_article_loadingplan_raw_oc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manningsheetdata',
            name='raw_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manningsheetdata',
            name='raw_oc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manningsheetdata',
            name='raw_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
