# Generated by Django 5.1.4 on 2025-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0024_alter_pushnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='notification_type',
            field=models.CharField(choices=[('dday_8_50', 'D-Day 8:50 AM Allocation Notification'), ('dday_12_45', 'D-day 12:45 PM Allocation Data'), ('dday_5_30', 'D-Day 5:30 PM Allocation Notification'), ('manning_sheet', 'Manning Sheet Allocation Notification'), ('absenteeism_prediction', 'Absenteeism Prediction Data')], max_length=50),
        ),
    ]
