# Generated by Django 5.1.4 on 2025-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0025_alter_pushnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unallocatedemployees',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
