# Generated by Django 5.1.4 on 2025-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0026_unallocatedemployees_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesOnHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_employees', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees_on_hold',
            },
        ),
    ]
