# Generated by Django 5.1.4 on 2025-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0027_employeesonhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesonhold',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
