# Generated by Django 5.1.4 on 2025-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0028_employeesonhold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesonhold',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
