# Generated by Django 5.1.4 on 2025-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning_sheet', '0029_employeesonhold_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddaydata',
            name='wip_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
